services:
  postgres:
    image: postgres:15-alpine
    container_name: billlens_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billlens
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: billlens_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
